spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:3306/warehouse_mg
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



server:
  port: 9999
  servlet:
    context-path: /uaa


eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka

#logging:
#  config: classpath:config/log4j2.xml
