eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8766
spring:
  application:
    name: warehouse-zuul

zuul:
  routes:
    userapi:
      path: /user/**
      serviceId: user-service
    feignapi:
      path: /feignapi/**
      serviceId: feign-user



