eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
server:
  port: 8763
spring:
  application:
    name: user-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://mysql:3306/warehouse_mg
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

mybatis:
  type-aliases-package: com.kone.utils.entity
  mapper-locations: classpath:mappers/*.xml

ribbon:
  eureka:
    enabled: true



#  product-service                        v1                  b285258027b1        10 hours ago        452 MB
#  material-service                       v1                  111ece649630        10 hours ago        452 MB
#  feign-user                             v1                  941e671256b8        10 hours ago        453 MB
#  order-service                          v1                  26efc2b46573        10 hours ago        453 MB
#  user-service                           v1                  758c88b5e272        10 hours ago        452 MB
#  config-server                          v1                  92b82e210ffc        11 hours ago        413 MB
#  eureka-server                          v1                  5ad48d66e5ad        11 hours ago        444 MB
#  hub.c.163.com/housan993/centos7_jdk8   latest              0f793ba5281b        14 months ago       356 MB
#  hub.c.163.com/library/ghost            latest              2e1ab1768f52        18 months ago       648 MB
#  hub.c.163.com/library/tomcat           latest              72d2be374029        19 months ago       292 MB
#  hub.c.163.com/library/redis            latest              d4f259423416        19 months ago       106 MB
#  hub.c.163.com/library/nginx            latest              46102226f2fd        22 months ago       109 MB
#  hub.c.163.com/library/mysql            latest              9e64176cd8a2        22 months ago       407 MB
#  hub.c.163.com/public/ubuntu            16.04-tools         1196ea15dad6        23 months ago       336 MB

