server:
  port: 8761
eureka:
  instance:
    hostname: eureka-server
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone:
        http://${eureka.instance.hostname}:${server.port}/eureka

ribbon:
  eureka:
    enabled: true