eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
server:
  port: 8765
spring:
  application:
    name: feign-user
  thymeleaf:
    cache: false

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000

feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true
  command:
    default:
     execution:
      isolation:
       thread:
         timeoutInMilliseconds: 12000
logging:
  config: classpath:config/log4j2.xml


